#weblogic
ORACLE_USER_PASSWORD: password
WEBLOGIC_USERNAME: weblogic
WEBLOGIC_PASSWORD: password

#RCU
DB_USER: admin
DB_PASSWORD: password
RCU_SCHEMA_PASSWORD: "{{ DB_PASSWORD }}"

#ODI
ODI_SUPERVISOR_PASS: password
SERVICE_DB_PASS: password
ODI_DB_PSWD: "{{ DB_PASSWORD }}"
ODI_PASSWORD: password

#OSM
OSM_CFS_ADMIN_PSWD: password
OSM_PROV_ADMIN_PSWD: password
OSM_CFS_WL_JMS_QUEUE_ACCESS_PSWD: password
OSM_PROV_WL_JMS_QUEUE_ACCESS_PSWD: password

#SBL EAI
XREF_SCHEMA_PASSWORD: aia
SBL_EAI_PSWD: 'password'
SBL_DB_PSWD: 'password'
SBL_EAI_PSWD_ENCODED: password
SBL_DB_PSWD_ENCODED: password

#BRM
BRM_AQ_USER: pin
BRM_AQ_PSWD: pin

#keystore
KeyStorePass: password
