---
- name: Copy LocalLoadBalancer.py files to the {{ SCRIPT_HOME }}
  template:
    src: LocalLoadBalancer.py.j2
    dest: "{{ SCRIPT_HOME }}/LocalLoadBalancer.py"
    mode: '+x'

- name: "invoke LocalLoadBalancer.py with WLST to update LB"
  shell: |
    . ./setWlstEnv.sh
    java weblogic.WLST {{ SCRIPT_HOME }}/LocalLoadBalancer.py > {{ LOGS_DIR }}/local_lb.log
  args:
    chdir: "{{ ORACLE_HOME }}/oracle_common/common/bin/"

- name: Wait until the string "completed" is in the file {{ LOGS_DIR }}/local_lb.log before continuing
  wait_for:
    path: "{{ LOGS_DIR }}/local_lb.log"
    search_regex: completed

- name: "Load Balancer Added"
  debug:
    msg: "LOAD BALANCER: {{ LOCAL_LOAD_BALANCER }} Added"